name: A workflow to build wasm for github pages
on:
    push: 
        branches:
            - master
        tags:
            - v*

jobs:
    build:
        name: Wasm build/deploy action
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - uses: ./wasm-action
          with:
            token: ${{ secrets.GITHUB_TOKEN }}